### ISSUE TITLE
手機版使用說明

### ISSUE THREAD

**Issue by seadog007** [TakeshiTseng/SitconSeatingChart#9]
用手機看使用說明的時候，因為是圖片縮放，所以會擠成一團![](http://i.imgur.com/Q1na0qJ.jpg)
我知道這很難修QQ

**Comment by iblis17** [comment]
圖片 不太想解....
@TakeshiTseng 你覺得呢？

**Comment by TakeshiTseng** [comment]
改成文字說明？

**Comment by seadog007** [comment]
不然就是用div疊上去

**Comment by TakeshiTseng** [comment]
@seadog007 你是說背景透明的 div ？

**Comment by seadog007** [comment]
對

**Comment by seadog007** [comment]
img也可

**Comment by TakeshiTseng** [comment]
因為不同手機看起來都會不一樣，目前打算直接把 img 拿掉，直接換成半透明灰色 div + 文字說明。
